#! /bin/bash

sudo port install mlpack

sudo pip install nltk

#FILE="mlpack-2.1.0.tar.gz"
#curl "http://mlpack.org/files/$FILE" >> $FILE
#tar xf "$FILE"
#rm $FILE
#
#FILE="armadillo-7.600.1.tar.xz"
#curl "http://sourceforge.net/projects/arma/files/$FILE" >> $FILE
#tar xJf "$FILE"
##rm $FILE
#
#brew install cmake
